services:
  ai-issue-genius-server:
    build: .
    container_name: ai-issue-genius-server
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c "uvicorn server:app --reload --host 0.0.0.0 --port 8000"
    ports:
      - :8000:8000
